### ISSUE TITLE
라이브러리 이름짓기

### ISSUE THREAD

**Issue by mojosoeun** [SE-Jr/tada.js#25]
라이브러리 이름 독특하면서, 재밌는 걸로 지어보죵 :)

**Comment by sososimsim** [comment]
- blossom
- merry
- butgoing(중의성ㅋㅋ)
- cherry
- merryCherry
- 세하 -동서남북 
- 바람개비
- 팽이
- 달팽이 
- inception
- green
- gabi
- circular line 
- circuit 
- track 
- cassette
- tape
- shuffle
- edm
- signal light
- traffic 
- yo
- 3seconds ? 8seconds
- 10minutes
- tadah 🎉
