### ISSUE TITLE
슬라이드가 여러개 생성 되었을 때 네비게이터는 독립적으로 동작해야 한다

### ISSUE THREAD

**Issue by ppyeonam** [SE-Jr/tada.js#30]
# 현재 상황
- 복수의 슬라이드를 생성하면 첫번째 객체에 네비게이터가 생성 됨
- 첫번째 `SP` 객체의 `.slide-wrap`을 기준으로 navigator가 추가 됨
- 인디케이터 클릭시 각각의 객체가 아닌 첫번째 객체에서 같은 동작이 일어남

**Comment by mojosoeun** [comment]
해결되어 이슈 닫도록 하겠습니다~
