### ISSUE TITLE
코딩 컨벤션

### ISSUE THREAD

**Issue by hyeonmi** [SE-Jr/tada.js#46]
### 안건
- 홀따옴표 대신에 쌍따옴표
- 들여쓰기 규칙, 2공백이냐 4공백이냐

**Comment by mojosoeun** [comment]
쌍따옴표 찬성입니다!
들여쓰기는 어떤 타입이 좋으시나요? 사실 지금은 tab을 사용하고 있었거든요~

**Comment by hyeonmi** [comment]
tab하면 공백으로 자동 바뀌는거 아니에요? 저는 4공백...

**Comment by hyeonmi** [comment]
기본적으로 공백 4개인데 airbnb 규칙은 공백 2개 입니다.
https://github.com/airbnb/javascript#whitespace--spaces
우리 프로젝트에서 airbnb lint를 확장하고 있어서 2개로 설정되어 있어요. 
그래서 규칙을 덮어 쓰도록 수정해야 합니다.

**Comment by mojosoeun** [comment]
이슈 닫을게용~
